#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

int isExecutable(char *input, char *tempPath, char *candidatePath, char *candidate) {
  char *myPath = strtok(tempPath, ":");
  while (myPath != NULL) {
    strcpy(candidatePath, myPath);
    strcat(candidatePath, "/");
    strcat(candidatePath, candidate);
    // printf("Checking: %s\n", candidatePath);
    if (access(candidatePath, X_OK) == 0) {
      return 1;
    }
    myPath = strtok(NULL, ":");
  }
  return 0;
}

int main(int argc, char *argv[]) {
  (stdout, NULL);// Flush after every printfsetbuf
  char input[100];
  char echo[] = "echo ";
  char *env_path = getenv("PATH");
  char *myPath; // pointer to the individual substrings generated by strtok()
  int typeFound = 0; // has the "type ..." thing been found
  int exists = 0;
  char tempPath[4096]; // to be used inside the while loop for local use and modification
  char candidatePath[1000]; // stores the substring being pointed to by myPath
  char *args[64];

  if (!env_path) {
    return 1;
  }

  char path[4096]; // store the $PATH stuff for local usage and modification
  char firstExec[100];

  snprintf(path, sizeof(path), "%s", env_path);

  while (1) {
    input[0] = '\0';
    strcpy(tempPath, path);
    printf("$ ");
    fgets(input, sizeof(input), stdin);
    input[strlen(input) - 1] = '\0'; // fets() also counts the enter('\n') input when done with a line, so it also prints the newline when writing the input onto the screen
    int firstSpace = strcspn(input, " ");
    strncpy(firstExec, input, firstSpace);
    firstExec[firstSpace + 1] = '\0';
    if (strcmp(input, "exit") == 0) {
      return 0;
    }

    // Better coding practice
    else if (strncmp(input, echo, 5) == 0) {
      printf("%s\n", input + 5);
    }

    else if (strncmp(input, "type ", 5) == 0) {
      typeFound = 0;

      if (strcmp(input + 5, "exit") == 0 || strcmp(input + 5, "echo") == 0 ||
          strcmp(input + 5, "type") == 0) {
        printf("%s is a shell builtin\n", input + 5);
        typeFound = 1;
      }

      // LOOP: read till you get a / for a file and till : for a new path
      // outer loop :

      if (typeFound == 0) {
        if (isExecutable(input, tempPath, candidatePath, input + 5)) {
          printf("%s is %s\n", input + 5, candidatePath);
          typeFound = 1;
        }
      }

      if (typeFound == 0) {
        printf("%s: not found\n", input + 5);
      }
    }

    else if (isExecutable(input, tempPath, candidatePath, firstExec)) {
      // printf("%s is an executable firstExec\n", firstExec);
      char *myPath = strtok(input, " ");
      int i = 0;
      while (myPath != NULL) {
        // printf("enterd while\n");
        args[i] = myPath;
        // printf("%s", args[i]);
        i++;
        myPath = strtok(NULL, " ");
      }
      args[i] = NULL;
      pid_t pid = fork();
      if (pid < 0) {
        perror("Fork Failed:");
        return 1;
      } else if (pid == 0) {
        if (execv(candidatePath, args) == -1) {
          perror("Execution Failed");
        }
        exit(EXIT_FAILURE);
      } else {
        int status;
        waitpid(pid, &status, 0);
      }
    }

    else {
      printf("%s: command not found\n", input);
    }
  }
  return 0;
}
