#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

int isExecutable(char *input, char *tempPath, char *candidatePath,
                 char *candidate) {
  char *myPath = strtok(tempPath, ":");
  while (myPath != NULL) {
    strcpy(candidatePath, myPath);
    strcat(candidatePath, "/");
    strcat(candidatePath, candidate);
    // printf("Checking: %s\n", candidatePath);
    if (access(candidatePath, X_OK) == 0) {
      return 1;
    }
    myPath = strtok(NULL, ":");
  }
  return 0;
}

void ifQuotes() {}

int main(int argc, char *argv[]) {
  setbuf(stdout, NULL); // recheck
  char cwd[1024];
  char input[100];
  char echo[] = "echo ";
  char *env_path = getenv("PATH");
  char *myPath; // pointer to the individual substrings generated by strtok()
  int typeFound = 0; // has the "type ..." thing been found
  int exists = 0;
  char tempPath[4096]; // to be used inside the while loop for local use and
                       // modification
  char candidatePath[1000]; // stores the substring being pointed to by myPath
  char *args[64];
  char username[100];
  char *home = getenv("HOME");
  char localHome[100];
  char quotedText[100];
  char quotedBuffer[100];
  if (!env_path) {
    return 1;
  }

  char path[4096]; // store the $PATH stuff for local usage and modification
  char firstExec[100];

  snprintf(path, sizeof(path), "%s", env_path);
  snprintf(localHome, sizeof(localHome), "%s", home);

  while (1) {
    input[0] = '\0';
    candidatePath[0] = '\0';
    strcpy(tempPath, path);
    printf("$ ");
    fgets(input, sizeof(input), stdin);
    input[strlen(input) - 1] =
        '\0'; // fets() also counts the enter('\n') input when done with a line,
              // so it also prints the newline when writing the input onto the
              // screen
    int firstSpace = strcspn(input, " ");
    strncpy(firstExec, input, firstSpace);
    firstExec[firstSpace] = '\0';
    if (strcmp(input, "exit") == 0) {
      return 0;
    }

    // Better coding practice
    else if (strncmp(input, echo, 5) == 0) {
      int j = 5;
      int i = 0;
      int quote = 0;
      int doubleQuote = 0;
      quotedText[0] = '\0';
      //"ronit's bag"
      //'ronit"s bag'
      int inQuote = 0;
      while (input[j] != '\0') {
        if (input[j] == '\'' && doubleQuote == 0) {
          quote = 1;
          inQuote = !inQuote;
          j++;
          continue;
        }
        if (input[j] == '\"' && quote == 0) {
          inQuote = !inQuote;
          doubleQuote = 1;
          j++;
          continue;
        }
        if (input[j] == ' ' && doubleQuote == 0 && quote == 0) {
          doubleQuote = 0;
        }
        if (input[j] == ' ' && input[j + 1] == ' ' && inQuote == 0) {
          j++;
          continue;
        }
        if (!inQuote) {
          if (input[j] == '\\') {
            j++;
            quotedText[i] = input[j];
            i++;
            j++;
            continue;
          }
        }
        quotedText[i] = input[j];
        i++;
        j++;
      }
      quotedText[i] = '\0';
      printf("%s\n", quotedText);
    }

    else if (strncmp(input, "cat ", 4) == 0) {
      int j = 4;
      int i = 0;
      int x = 1;
      int quote = 0;
      int doubleQuote = 0;
      int inQuote = 0;
      int p = 0;
      args[0] = "cat";
      quotedBuffer[0] = '\0';
      // 'file1' file2\0
      // cat '/tmp/bee/f   61' '/tmp/bee/f   88' '/tmp/bee/f   22'
      // cat /tmp/dog/\_ignored_2 /tmp/dog/ignore_\18 /tmp/dog/just_one_\\_92
      //"ronit's bag"
      while (input[j] != '\0') {
        if (quote == 1) {
          if (input[j] == '\"') {
            quotedBuffer[i] = input[j];
            i++;
            j++;
            continue;
          }
          if (input[j] == '\'') {
            quotedBuffer[i] = '\0';
            j++;
            args[x] = strdup(quotedBuffer);
            x++;
            quote = 0;
            i = 0;
            quotedBuffer[0] == '\0';
            continue;
          }
        }
        if (doubleQuote == 1) {
          if (input[j] == '\'') {
            quotedBuffer[i] = input[j];
            i++;
            j++;
            continue;
          }
          if (input[j] == '\"') {
            quotedBuffer[i] = '\0';
            j++;
            args[x] = strdup(quotedBuffer);
            x++;
            doubleQuote = 0;
            i = 0;
            quotedBuffer[0] = '\0';
            continue;
          }
        }

        if (doubleQuote == 0 && input[j] == '\'') { // outside "" found a '
          quote = 1;
          j++;
          quotedBuffer[i] = input[j];
          i++;
          j++;
          continue;
        }

        if (quote == 0 && input[j] == '\"') {
          doubleQuote = 1;
          j++;
          quotedBuffer[i] = input[j];
          i++;
          j++;
          continue;
        }

        if (doubleQuote == 0 && quote == 0) {
          if (input[j] == ' ') {
            if (input[j - 1] != '\'' && input[j - 1] != '\"') {
              quotedBuffer[i] = '\0';
              args[x] = strdup(quotedBuffer);
              x++;
              quotedBuffer[0] = '\0';
              i = 0;
              j++;
              continue;
            }
            j++; // incase it's an unquoted path
            continue;
          }
          if (input[j] == '\\') {
            j++;
            quotedBuffer[i] = input[j];
            i++;
            j++;
            continue;
          }
        }

        quotedBuffer[i] = input[j];
        i++;
        j++;
        if (input[j] == '\0') {
          quotedBuffer[i] = '\0';
          args[x] = strdup(quotedBuffer);
          x++;
        }
      }
      // for(int k = 0; k<x; k++){
      //   printf("[%s]", args[k]);
      // }
      args[x] = NULL;
      pid_t pid = fork();
      if (pid < 0) {
        perror("Fork Failed:");
        return 1;
      } else if (pid == 0) {
        if (execv("/usr/bin/cat", args) == -1) {
          perror("Execution Failed");
        }
        exit(EXIT_FAILURE);
      } else {
        int status;
        waitpid(pid, &status, 0);
      }
    }

    else if (strcmp(input, "pwd") == 0) {
      getcwd(cwd, sizeof(cwd));
      printf("%s\n", cwd);
    }

    else if (strncmp(input, "cd ", 3) == 0) {
      if (strcmp(input + 3, "~") == 0) {
        chdir(localHome);
        continue;
      }
      if (chdir(input + 3) != 0) {
        fprintf(stderr, "cd: %s: %s\n", (input + 3), strerror(errno));
      }
    }

    else if (strncmp(input, "type ", 5) == 0) {
      typeFound = 0;

      if (strcmp(input + 5, "exit") == 0 || strcmp(input + 5, "echo") == 0 ||
          strcmp(input + 5, "type") == 0 || strcmp(input + 5, "pwd") == 0) {
        printf("%s is a shell builtin\n", input + 5);
        typeFound = 1;
      }

      // LOOP: read till you get a / for a file and till : for a new path
      // outer loop :

      if (typeFound == 0) {
        if (isExecutable(input, tempPath, candidatePath, input + 5)) {
          printf("%s is %s\n", input + 5, candidatePath);
          typeFound = 1;
        }
      }

      if (typeFound == 0) {
        printf("%s: not found\n", input + 5);
      }
    }

    else if (isExecutable(input, tempPath, candidatePath, firstExec)) {
      // printf("%s is an executable firstExec\n", firstExec);
      char *myPath = strtok(input, " ");
      int i = 0;
      while (myPath != NULL) {
        // printf("enterd while\n");
        args[i] = myPath;
        // printf("%s", args[i]);
        i++;
        myPath = strtok(NULL, " ");
      }
      args[i] = NULL;
      pid_t pid = fork();
      if (pid < 0) {
        perror("Fork Failed:");
        return 1;
      } else if (pid == 0) {
        if (execv(candidatePath, args) == -1) {
          perror("Execution Failed");
        }
        exit(EXIT_FAILURE);
      } else {
        int status;
        waitpid(pid, &status, 0);
      }
    }

    else {
      printf("%s: command not found\n", input);
    }
  }
  return 0;
}